# Generated by Django 6.0.6 on 2026-06-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_pos', '0002_seed_demo_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_of_measure',
            field=models.CharField(choices=[('per piece', 'Per piece'), ('per cup', 'Per cup'), ('per glass', 'Per glass'), ('per plate', 'Per plate'), ('per bowl', 'Per bowl'), ('per slice', 'Per slice'), ('per serving', 'Per serving'), ('per packet', 'Per packet'), ('per bottle', 'Per bottle'), ('per kilogram', 'Per kilogram'), ('per gram', 'Per gram'), ('per litre', 'Per litre'), ('per millilitre', 'Per millilitre')], max_length=20),
        ),
    ]
