# Generated by Django 5.2.15 on 2026-06-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_pos', '0003_alter_product_unit_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
