# Generated by Django 6.0.6 on 2026-06-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_pos', '0003_alter_product_unit_of_measure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafetable',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='cafetable',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Order within the floor.'),
        ),
    ]
