# Generated by Django 5.2.15 on 2026-06-13 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_pos', '0004_product_image'),
        ('tenants', '0003_cafe_custom_css_cafe_theme_accent_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(blank=True, help_text='UPI VPA used for the POS QR, e.g. cafe@ybl', max_length=100)),
                ('upi_payee_name', models.CharField(blank=True, help_text='Name shown in the UPI app.', max_length=100)),
                ('razorpay_enabled', models.BooleanField(default=False)),
                ('razorpay_key_id', models.CharField(blank=True, max_length=120)),
                ('razorpay_key_secret', models.CharField(blank=True, max_length=120)),
                ('stripe_enabled', models.BooleanField(default=False)),
                ('stripe_publishable_key', models.CharField(blank=True, max_length=160)),
                ('stripe_secret_key', models.CharField(blank=True, max_length=160)),
                ('cafe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_settings', to='tenants.cafe')),
            ],
            options={
                'verbose_name': 'Payment settings',
                'verbose_name_plural': 'Payment settings',
            },
        ),
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_default', models.BooleanField(default=True, help_text='Use the built-in receipt design.')),
                ('template_html', models.TextField(blank=True, help_text='Custom receipt HTML with {{ data pills }}.')),
                ('smtp_use_default', models.BooleanField(default=True, help_text="Send via the platform's default email.")),
                ('smtp_host', models.CharField(blank=True, max_length=120)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=160)),
                ('smtp_password', models.CharField(blank=True, max_length=200)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('from_email', models.CharField(blank=True, help_text='e.g. Cafe <orders@cafe.com>', max_length=200)),
                ('cafe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_settings', to='tenants.cafe')),
            ],
            options={
                'verbose_name': 'Receipt settings',
                'verbose_name_plural': 'Receipt settings',
            },
        ),
    ]
