# Generated by Django 6.0.5 on 2026-06-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_pos', '0005_paymentsettings_receiptsettings'),
        ('cafe_pos', '0005_product_image'),
    ]

    operations = [
    ]
