# Generated by Django 5.2.15 on 2026-06-13 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_pos', '0004_alter_cafetable_options_cafetable_sort_order'),
        ('cafe_pos', '0005_paymentsettings_receiptsettings'),
    ]

    operations = [
    ]
