# Generated by Django 5.2.15 on 2026-06-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_pos', '0006_merge_20260613_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='method_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('razorpay', 'Razorpay')], max_length=10),
        ),
    ]
