# Generated by Django 6.0.6 on 2026-06-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_pos', '0008_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent_to_kitchen', 'Sent to Kitchen'), ('ready', 'Ready'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
