# Generated by Django 5.2.15 on 2026-06-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_pos', '0009_alter_order_status'),
        ('cafe_pos', '0009_coupon_name'),
    ]

    operations = [
    ]
