# Generated by Django 5.2.15 on 2026-06-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_pos', '0011_profile_kitchen_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafetable',
            name='is_occupied',
            field=models.BooleanField(default=False, help_text='Locked by staff until table is manually cleared.'),
        ),
    ]
