# Generated by Codex on 2026-06-13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def create_default_loyalty_settings(apps, schema_editor):
    Cafe = apps.get_model("tenants", "Cafe")
    LoyaltySettings = apps.get_model("cafe_pos", "LoyaltySettings")
    for cafe in Cafe.objects.all():
        LoyaltySettings.objects.get_or_create(cafe=cafe)


def delete_default_loyalty_settings(apps, schema_editor):
    LoyaltySettings = apps.get_model("cafe_pos", "LoyaltySettings")
    LoyaltySettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_cafe_custom_css_cafe_theme_accent_color_and_more"),
        ("cafe_pos", "0012_table_is_occupied"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltySettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level_1_orders", models.PositiveIntegerField(default=1)),
                ("level_2_orders", models.PositiveIntegerField(default=3)),
                ("level_3_orders", models.PositiveIntegerField(default=10)),
                ("level_4_orders", models.PositiveIntegerField(default=20)),
                ("level_5_orders", models.PositiveIntegerField(default=50)),
                ("points_per_order", models.PositiveIntegerField(default=10)),
                ("cafe", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="loyalty_settings", to="tenants.cafe")),
            ],
            options={
                "verbose_name": "Loyalty settings",
                "verbose_name_plural": "Loyalty settings",
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="ban_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="manual_loyalty_level",
            field=models.PositiveSmallIntegerField(blank=True, help_text="Optional admin override for this customer's loyalty level.", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.RunPython(create_default_loyalty_settings, delete_default_loyalty_settings),
    ]
