# Generated by Django 5.2.15 on 2026-06-13 18:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_pos', '0014_order_review_token_orderlineitem_prepared_by_and_more'),
        ('tenants', '0003_cafe_custom_css_cafe_theme_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptsettings',
            name='feedback_email_html',
            field=models.TextField(blank=True, help_text='Custom feedback email HTML.'),
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('rating', 'Star Rating (1-5)'), ('text', 'Text Input')], max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_questions', to='tenants.cafe')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text_value', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe_pos.feedbackquestion')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='cafe_pos.orderreview')),
            ],
        ),
    ]
