# Generated by Django 5.2.15 on 2026-06-13 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_pos', '0015_receiptsettings_feedback_email_html_feedbackquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreview',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
