# Generated by Django 5.2.15 on 2026-06-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_pos', '0016_alter_orderreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafetable',
            name='height',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='cafetable',
            name='shape',
            field=models.CharField(choices=[('rectangle', 'Rectangle'), ('circle', 'Circle')], default='rectangle', max_length=20),
        ),
        migrations.AddField(
            model_name='cafetable',
            name='width',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='cafetable',
            name='x_pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cafetable',
            name='y_pos',
            field=models.IntegerField(default=0),
        ),
    ]
