# Generated by Django 5.2.15 on 2026-06-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_pos', '0017_cafetable_height_cafetable_shape_cafetable_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafetable',
            name='x_pos',
        ),
        migrations.RemoveField(
            model_name='cafetable',
            name='y_pos',
        ),
        migrations.AddField(
            model_name='cafetable',
            name='pos_x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cafetable',
            name='pos_y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='floor',
            name='canvas_mode',
            field=models.BooleanField(default=False, help_text='If true, displays tables on an interactive grid canvas instead of a list.'),
        ),
        migrations.AlterField(
            model_name='cafetable',
            name='height',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='cafetable',
            name='shape',
            field=models.CharField(choices=[('rect', 'Rectangle'), ('circle', 'Circle')], default='rect', max_length=20),
        ),
        migrations.AlterField(
            model_name='cafetable',
            name='width',
            field=models.FloatField(default=100.0),
        ),
    ]
