# Generated by Django 5.2.15 on 2026-06-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_pos', '0019_chatassistantsettings_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cross_sells',
            field=models.ManyToManyField(blank=True, related_name='recommended_with', to='cafe_pos.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Mark as Featured or Chef's Special"),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g. Spicy, Vegan, Bestseller)', max_length=255, null=True),
        ),
    ]
