# Generated by Django 6.0.5 on 2026-06-13 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_pos', '0021_customreceipttheme_themepurchase'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='themepurchase',
            name='uniq_purchase_per_cafe_theme',
        ),
        migrations.RemoveField(
            model_name='themepurchase',
            name='cafe',
        ),
        migrations.RemoveField(
            model_name='themepurchase',
            name='theme',
        ),
        migrations.DeleteModel(
            name='CustomReceiptTheme',
        ),
        migrations.DeleteModel(
            name='ThemePurchase',
        ),
    ]
