# Generated by Django 5.2.15 on 2026-06-13 08:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedSubdomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, unique=True)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Reserved subdomain',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('subdomain', models.CharField(blank=True, help_text='The <this>.kuba.com host. Leave blank to auto-generate.', max_length=63, unique=True)),
                ('custom_domain', models.CharField(blank=True, help_text='Optional full custom host, e.g. mcd.kuba.com. Superuser only.', max_length=255, null=True, unique=True)),
                ('logo_svg', models.TextField(blank=True, help_text='Inline SVG markup for the cafe logo (editable).')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='cafe_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(blank=True, help_text='The cafe administrator account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_cafes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('signup', 'Signup'), ('other', 'Other')], default='other', max_length=20)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('cafe', models.ForeignKey(blank=True, help_text='Null for platform-level actions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.cafe')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
