# Generated by Django 5.2.15 on 2026-06-13 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_seed_reserved_subdomains'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='custom_css',
            field=models.TextField(blank=True, help_text="Advanced per-cafe CSS overrides. Loaded only on this cafe's host."),
        ),
        migrations.AddField(
            model_name='cafe',
            name='theme_accent_color',
            field=models.CharField(default='#6b8c5a', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #c8903e.', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AddField(
            model_name='cafe',
            name='theme_primary_color',
            field=models.CharField(default='#c8903e', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #c8903e.', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AddField(
            model_name='cafe',
            name='theme_primary_hover_color',
            field=models.CharField(default='#e0a855', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #c8903e.', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AddField(
            model_name='cafe',
            name='theme_radius_px',
            field=models.PositiveSmallIntegerField(default=14, help_text='Base corner radius in pixels.', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AddField(
            model_name='cafe',
            name='theme_sidebar_color',
            field=models.CharField(default='#2c1e0f', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #c8903e.', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AddField(
            model_name='cafe',
            name='theme_surface_alt_color',
            field=models.CharField(default='#f5efe6', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #c8903e.', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AddField(
            model_name='cafe',
            name='theme_surface_color',
            field=models.CharField(default='#faf7f0', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #c8903e.', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AddField(
            model_name='cafe',
            name='theme_text_color',
            field=models.CharField(default='#1a1209', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #c8903e.', regex='^#[0-9a-fA-F]{6}$')]),
        ),
    ]
