# Generated by Django 6.0.5 on 2026-06-13 20:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_cafe_custom_css_cafe_theme_accent_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReceiptTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price in USD / flat fee', max_digits=8)),
                ('html_content', models.TextField(help_text='HTML template for the receipt. Can use placeholders.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Custom Receipt Theme',
                'verbose_name_plural': 'Custom Receipt Themes',
                'db_table': 'cafe_pos_customreceipttheme',
            },
        ),
        migrations.CreateModel(
            name='ThemePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, help_text='Active license status')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_purchases', to='tenants.cafe')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='tenants.customreceipttheme')),
            ],
            options={
                'verbose_name': 'Theme Purchase',
                'verbose_name_plural': 'Theme Purchases',
                'db_table': 'cafe_pos_themepurchase',
                'constraints': [models.UniqueConstraint(fields=('cafe', 'theme'), name='uniq_purchase_per_cafe_theme')],
            },
        ),
    ]
