"""
Django settings for kuba project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import unquote, urlparse
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


def _csv_env(name):
    return [item.strip() for item in os.environ.get(name, '').split(',') if item.strip()]


def _truthy(value):
    return str(value).strip().lower() in {'1', 'true', 'yes', 'on'}


def _database_config_from_url(database_url):
    parsed = urlparse(database_url)
    if parsed.scheme in {'postgres', 'postgresql'}:
        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed.path.lstrip('/'),
            'USER': unquote(parsed.username or ''),
            'PASSWORD': unquote(parsed.password or ''),
            'HOST': parsed.hostname or '',
            'PORT': str(parsed.port or ''),
            'CONN_MAX_AGE': int(os.environ.get('CONN_MAX_AGE', '600')),
            'OPTIONS': {'sslmode': 'require'},
        }
    if parsed.scheme == 'sqlite':
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': Path(unquote(parsed.path)),
        }
    raise ValueError(f'Unsupported DATABASE_URL scheme: {parsed.scheme}')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-change-me-on-render')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _truthy(os.environ.get('DEBUG', 'True'))

# ─── Multi-tenant / subdomain configuration ──────────────────────────────
# Cafes live at <subdomain>.<KUBA_BASE_DOMAIN>; the Django admin lives at
# <KUBA_ADMIN_SUBDOMAIN>.<KUBA_BASE_DOMAIN>. Locally, *.localhost works too.
KUBA_BASE_DOMAIN = os.environ.get('KUBA_BASE_DOMAIN', 'kuba.com')
KUBA_ADMIN_SUBDOMAIN = os.environ.get('KUBA_ADMIN_SUBDOMAIN', 'admin')
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '').strip()

ALLOWED_HOSTS = _csv_env('DJANGO_ALLOWED_HOSTS') or [
    f'.{KUBA_BASE_DOMAIN}',  # kuba.com and every *.kuba.com subdomain
    '.localhost',            # *.localhost for local subdomain testing
    'localhost',
    '127.0.0.1',
]
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CSRF_TRUSTED_ORIGINS = _csv_env('DJANGO_CSRF_TRUSTED_ORIGINS') or [
    f'https://{KUBA_BASE_DOMAIN}',
    f'https://*.{KUBA_BASE_DOMAIN}',
]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# Allow same-origin iframes (dashboard embeds POS/KDS)
X_FRAME_OPTIONS = 'SAMEORIGIN'


# Application definition

INSTALLED_APPS = [
    'daphne',
    'jazzmin',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'tenants',
    'dashboard',
    'cafe_pos',
    'pos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tenants.middleware.TenantMiddleware',
    'tenants.middleware.AdminAccessMiddleware',
]

ROOT_URLCONF = 'kuba.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tenants.context_processors.tenant',
            ],
        },
    },
]

WSGI_APPLICATION = 'kuba.wsgi.application'
ASGI_APPLICATION = 'kuba.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

REDIS_URL = os.environ.get('REDIS_URL', '').strip()
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': _database_config_from_url(os.environ['DATABASE_URL'])
    if os.environ.get('DATABASE_URL')
    else {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = Path(os.environ.get('STATIC_ROOT', str(BASE_DIR / 'staticfiles')))
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'stock',  # Videos & screenshots for landing page
]
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', str(BASE_DIR / 'media')))

# ─── Email ────────────────────────────────────────────────────────────────
# Platform default SMTP (from .env). Cafes may override with their own SMTP in
# their Receipt settings; this is the fallback connection.
APP_NAME = os.environ.get('APP_NAME', 'kuba')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com').strip()
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').strip().lower() in {'1', 'true', 'yes', 'on'}
EMAIL_USE_SSL = EMAIL_PORT == 465
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '').strip()
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', f'{APP_NAME} <{EMAIL_HOST_USER}>')
EMAIL_TIMEOUT = 15
# Use real SMTP when credentials are present; otherwise print emails to the console.
EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend'
    if EMAIL_HOST_USER
    else 'django.core.mail.backends.console.EmailBackend'
)

# ─── django-allauth configuration ────────────────────────────────────────
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Change to 'mandatory' in production
ACCOUNT_LOGOUT_ON_GET = True

# Self-service signup creates a cafe; the adapter routes users to their cafe host.
# Login is subdomain-locked (CafeLoginForm refuses non-members of the current cafe).
ACCOUNT_FORMS = {
    'signup': 'tenants.forms.CafeSignupForm',
    'login': 'tenants.forms.CafeLoginForm',
}
ACCOUNT_ADAPTER = 'tenants.adapters.KubaAccountAdapter'

# ─── Jazzmin (admin UI) ───────────────────────────────────────────────────
JAZZMIN_SETTINGS = {
    'site_title': 'Kuba Admin',
    'site_header': 'Kuba Platform',
    'site_brand': 'Kuba',
    'welcome_sign': 'Welcome to the Kuba platform admin',
    'copyright': 'Kuba',
    'search_model': ['tenants.Cafe', 'auth.User'],
    'show_sidebar': True,
    'navigation_expanded': True,
    'order_with_respect_to': ['tenants', 'cafe_pos', 'auth'],
    'icons': {
        'tenants.Cafe': 'fas fa-store',
        'tenants.ReservedSubdomain': 'fas fa-lock',
        'tenants.AuditLog': 'fas fa-clipboard-list',
        'auth.User': 'fas fa-user',
        'auth.Group': 'fas fa-users',
    },
    'topmenu_links': [
        {'name': 'Cafes', 'model': 'tenants.Cafe'},
    ],
}
JAZZMIN_UI_TWEAKS = {
    'theme': 'flatly',
    'navbar_small_text': False,
    'sidebar_nav_flat_style': True,
}
