"""
Django settings for kuba project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z9wnpqj(-7a9ar98jt!+^4m$93o3(kll5sp@kn!z3w9)zpb$pt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ─── Multi-tenant / subdomain configuration ──────────────────────────────
# Cafes live at <subdomain>.<KUBA_BASE_DOMAIN>; the Django admin lives at
# <KUBA_ADMIN_SUBDOMAIN>.<KUBA_BASE_DOMAIN>. Locally, *.localhost works too.
KUBA_BASE_DOMAIN = os.environ.get('KUBA_BASE_DOMAIN', 'kuba.com')
KUBA_ADMIN_SUBDOMAIN = os.environ.get('KUBA_ADMIN_SUBDOMAIN', 'admin')

ALLOWED_HOSTS = [
    f'.{KUBA_BASE_DOMAIN}',  # kuba.com and every *.kuba.com subdomain
    '.localhost',            # *.localhost for local subdomain testing
    'localhost',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'tenants',
    'dashboard',
    'cafe_pos',
    'pos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tenants.middleware.TenantMiddleware',
    'tenants.middleware.AdminAccessMiddleware',
]

ROOT_URLCONF = 'kuba.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tenants.context_processors.tenant',
            ],
        },
    },
]

WSGI_APPLICATION = 'kuba.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ─── Email (console backend for development) ─────────────────────────────
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ─── django-allauth configuration ────────────────────────────────────────
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Change to 'mandatory' in production
ACCOUNT_LOGOUT_ON_GET = True

# Self-service signup creates a cafe; the adapter routes users to their cafe host.
ACCOUNT_FORMS = {'signup': 'tenants.forms.CafeSignupForm'}
ACCOUNT_ADAPTER = 'tenants.adapters.KubaAccountAdapter'

# ─── Jazzmin (admin UI) ───────────────────────────────────────────────────
JAZZMIN_SETTINGS = {
    'site_title': 'Kuba Admin',
    'site_header': 'Kuba Platform',
    'site_brand': 'Kuba',
    'welcome_sign': 'Welcome to the Kuba platform admin',
    'copyright': 'Kuba',
    'search_model': ['tenants.Cafe', 'auth.User'],
    'show_sidebar': True,
    'navigation_expanded': True,
    'order_with_respect_to': ['tenants', 'cafe_pos', 'auth'],
    'icons': {
        'tenants.Cafe': 'fas fa-store',
        'tenants.ReservedSubdomain': 'fas fa-lock',
        'tenants.AuditLog': 'fas fa-clipboard-list',
        'auth.User': 'fas fa-user',
        'auth.Group': 'fas fa-users',
    },
    'topmenu_links': [
        {'name': 'Cafes', 'model': 'tenants.Cafe'},
    ],
}
JAZZMIN_UI_TWEAKS = {
    'theme': 'flatly',
    'navbar_small_text': False,
    'sidebar_nav_flat_style': True,
}